# Original work by: EnterpriseDB
# Author: Doug Ortiz
# Date: March 03, 2022
# Version: 1.0
# Copyright (c) 2020 EnterpriseDB

- hosts: localhost

  vars_files:
    - ./variables.yml

  tasks:
#  - name: Print token
#    debug: msg="{{ token }}"
    
  - name: List BigAnimal Clusters
    uri:
      url: "{{ biganimal_server }}{{ list_endpoint }}"
      method: GET
      headers:
        Authorization: "Bearer {{ token }}"      
        Cache-Control: no-cache
        Connection: keep-alive
      return_content: yes
      validate_certs: no
      force_basic_auth: yes
      follow_redirects: yes
      status_code: 200
      timeout: 30
    register: provision_results

  - name: BigAnimal Cluster List
    debug:
      var: provision_results
