# Original work by: EnterpriseDB
# Author: Doug Ortiz
# Date: March 03, 2022
# Version: 1.0
# Copyright (c) 2020 EnterpriseDB

- hosts: localhost

  vars_files:
    - ./variables.yml

  tasks:
#  - name: Print token
#    debug: msg="{{ token }}"
    
  - name: Provision  BigAnimal Cluster
    uri:
      url: "{{ biganimal_server }}{{ provision_endpoint }}"
      method: POST
      body: "{{ lookup('file', 'data.json') }}"
      body_format: json      
      headers:
        Authorization: "Bearer {{ token }}"      
        Cache-Control: no-cache
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive
        Accept: application/json
      return_content: yes
      status_code: 202
      timeout: 30
    register: provision_results

  - name: BigAnimal Cluster pgId
    debug:
      var: provision_results.json.pgId
